# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~

        # the name of the "filter set"
        filter_1 :

            # adjust the image quality to 75%
            quality : 100

            # list of transformations to apply (the "filters")
            filters :

                # create a thumbnail: set size to 500x100 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [300, 200], mode : outbound }
